### PR TITLE
Refactoring + Remove Delayed Extensions

### PR DESCRIPTION
**Pull request by agius**
Supersedes #55 in a less hacky way. The `.delay` / `.delay_for` was hiding some complexity - it allowed us to treat subscribers that send `Mail::Message` and ones that don't the same way. Now we have to handle sending emails ourselves. 

I took the opportunity to tease apart some of this functionality, and simplify the building & tracking of dynamic handler / worker classes, and move towards less monolithic objects. There's more to be done, but trying not to let refactoring scope totally blow up. Had to prototype a few different architectures, so this wasn't exactly TDD'd - writing specs now, but would love some feedback on how it looks.

/cc @wnadeau , @joelmichael , @heythisisnate 

Lots of the diff are not actual changes, just shuffling code around and changing some style things. Here are actual changes / refactors:

* Extract things from `Subscribable` into the `Subscription` object, which will store the options passed to `on_event` and build the handler class
* Handlers are now built by inheriting from an abstract class (`lib/workers/event_handler.rb`) and setting options on it instead of dynamic `define_method` and such
* Split workers that handle mailers vs generic event workers - branching functionality that was previously hidden by `.delay_for`
* Move `on_fire` handling for database subscribers to a separate worker class to get rid of `.delay` there

Let me know if you'd like a walk-through or want to :pear:

### CODE REVIEW

**Comment by heythisisnate** [comment]
I think this looks pretty great! It's a little tough to grok all the changes here just by reading the diff because it's been a while since I've been deep in Reactor code.

It _looks like_ this just reorganizes things but keeps the same worker class naming scheme. Is that right? My main concern is backwards-incompatible changes, because when we deploy this there will be jobs serialized in the queue that the new code needs to still support.

**Comment by agius** [comment]
> My main concern is backwards-incompatible changes

This aims for fully backwards-compatible - patch release. I have a PR on our main app with no changes besides changing Reactor to this branch. That's been pretty successful for updating and refactoring [stretchy](https://github.com/hired/stretchy), so I think it'll work here as well.

> It's a little tough to grok all the changes here just by reading the diff 

Yeah, an awful lot of the "changes" here are changing the definition syntax and moving things one tab in:

```ruby
# changing this:
class Reactor::Subscribable
  # define stuff
end

# to this
module Reactor
  class Subscribable
    # define stuff
  end
end
```

This is the syntax I've seen in a lot of open source libraries (ex: [Sidekiq](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/extensions/active_record.rb) ). It's a [default cop](http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/ClassAndModuleChildren) in Rubocop. The main reason (I think) is that it makes it easier to re-order files, since you don't have to worry about the module being defined before that file is required.

Also shuffling code around - moving errors to their own file, adding module files (`lib/reactor/models.rb`) etc. Updated the PR description to better explain the actual changes.

**Comment by satyap2** [comment]
> you don't have to worry about the module being defined before that file is required.

❤️ 

And good job doing multiple commits! Makes it easier to follow a large PR.

**Comment by heythisisnate** [comment]
🎉

**Pull request merged**
