### PR TITLE
Upgrade vulnerable gems

### PR DESCRIPTION
**Pull request by joelmichael**
rails-html-sanitizer and loofah.

### CODE REVIEW

**Comment by joelmichael** [comment]
The frick are these test failures.

**Comment by davidrunger** [comment]
Weird. I kicked off a build of `master`; let's see if that passes: https://travis-ci.org/hired/reactor/builds/350139665

**Comment by davidrunger** [comment]
Update: nope, `master` fails, too, with the same failures as on your branch, for example:

```
An error occurred while loading ./spec/event_spec.rb.
Failure/Error: ActiveRecord::Migrator.up "db/migrate"
NoMethodError:
  undefined method `up' for ActiveRecord::Migrator:Class
# ./spec/support/active_record.rb:5:in `<top (required)>'
# ./spec/spec_helper.rb:5:in `require'
# ./spec/spec_helper.rb:5:in `<top (required)>'
# ./spec/event_spec.rb:1:in `require'
# ./spec/event_spec.rb:1:in `<top (required)>'
```

**Comment by joelmichael** [comment]
Master has started failing for the exact same unrelated reason https://travis-ci.org/hired/reactor/jobs/350139666

**Comment by joelmichael** [comment]
Lol David out of nowhere. Thanks for looking into it

**Pull request merged**
