### PR TITLE
Use RSpec 3.2

### PR DESCRIPTION
**Pull request by joelmichael**
Change how expectations block is passed to subscribe_to matcher.
Bump version to 0.9.8.

### CODE REVIEW

**Comment by joelmichael** [comment]
@wnadeau pls review

**Comment by joelmichael** [comment]
it doesn't work despite the tests passing...

**Comment by joelmichael** [comment]
works now

**Comment by wnadeau** [comment]
if the build passes in Hired, lgtm! :+1: :+1:

**Pull request merged**
