### PR TITLE
Update gems

### PR DESCRIPTION
**Pull request by joelmichael**
Also remove Gemfile.lock from .gitignore.
And increase version restriction on rspec.

### CODE REVIEW

**Comment by joelmichael** [comment]
bot review me @hired/systems

**Comment by joelmichael** [comment]
pls review @heythisisnate

**Comment by heythisisnate** [comment]
:+1: 
Wow. Why was the Gemfile.lock originally excluded?

**Comment by joelmichael** [comment]
-shrug-

**Pull request merged**
